import Image from "next/image";
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Check, ChevronRight, Code2, Download, ExternalLink, Network, Phone, Server } from "lucide-react";
import { GithubMark, PortfolioHeader } from "@/components/portfolio-interactive";
import { ProjectGallery } from "@/components/project-gallery";
import { capabilities, projects, technologies, type PortfolioProject } from "@/lib/portfolio-data";

export default function PortfolioPage() {
  return <main className="site-shell">
    <PortfolioHeader />

    <section id="top" className="hero-section section-frame">
      <div className="hero-grid-line" />
      <div className="hero-content">
        <p className="eyebrow"><span className="eyebrow-line" /> Software engineer · Product builder</p>
        <h1>I engineer the systems<span>people trust.</span></h1>
        <p className="hero-lead">I&apos;m Bassam Alhakim — a systems-minded full-stack engineer working across Laravel, Next.js, Flutter, IoT, data, and product experience. I turn complex operations into software that feels clear, capable, and built to last.</p>
        <div className="hero-actions"><a href="#work" className="button button-primary">Explore selected work <ArrowDown size={16} /></a><a href="/Bassam_Alhakim_Systems_Engineer_CV.pdf" download className="button button-light"><Download size={16} /> Download résumé</a></div>
        <div className="hero-proof"><div><strong>10</strong><span>selected systems</span></div><div><strong>15+</strong><span>repositories</span></div><div><strong>7</strong><span>technology areas</span></div></div>
      </div>
      <div className="hero-portrait-wrap"><div className="portrait-card"><div className="portrait-meta"><span>BASSAM ALHAKIM</span><span>SYSTEMS ENGINEER</span></div><div className="portrait-image"><Image src="/developer-hero-576.webp" alt="Bassam Alhakim, software engineer" fill priority fetchPriority="high" unoptimized sizes="(max-width: 900px) 82vw, 420px" className="object-cover object-top" /></div><div className="portrait-footer"><span>Yemen · Remote</span><span>Software systems</span></div></div></div>
      <div className="hero-index"><span>Scroll to explore</span><ArrowDown size={16} /></div>
    </section>

    <section id="about" className="manifesto-section section-frame"><div className="section-kicker"><span>01</span><span>What I care about</span></div><div className="manifesto-layout"><h2>Good engineering should feel <em>inevitable.</em></h2><div className="manifesto-copy"><p>I work at the intersection of product thinking and software engineering. The goal is never to add complexity for its own sake; it is to make ambitious ideas easier to understand, operate, and grow.</p><p>From enterprise workflows to immersive commerce, I bring structure to the hard parts and taste to the visible ones.</p><a href="#contact" className="text-link">Let&apos;s make something considered <ArrowUpRight size={15} /></a></div></div></section>

    <section id="approach" className="approach-section section-frame"><div className="section-kicker"><span>02</span><span>Engineering range</span></div><div className="section-heading-row"><div><p className="eyebrow">The stack is only the beginning</p><h2>Depth across<br /><span>the whole build.</span></h2></div><p className="section-intro">From the first product decision to the last operational detail, I work across the layers that make software useful: interface, backend, data, deployment, and the systems around them.</p></div><div className="capability-grid">{capabilities.map((capability, index) => { const Icon = [Network, Code2, Server][index]; return <article key={capability.title} className="capability-card"><span className="card-number">0{index + 1}</span><Icon size={23} strokeWidth={1.5} /><h3>{capability.title}</h3><p>{capability.description}</p><span className="card-arrow"><ChevronRight size={16} /></span></article>; })}</div><div className="expertise-panel"><div className="expertise-panel-heading"><span className="tech-label">Core technologies</span><span className="expertise-note">Selected by the problem, not the trend</span></div><div className="expertise-grid"><div><span className="expertise-group-label">Product & web</span><strong>Next.js · React · TypeScript</strong><small>Commerce, dashboards, editorial systems, motion-led interfaces.</small></div><div><span className="expertise-group-label">Backend & data</span><strong>Laravel · PHP · Prisma · PostgreSQL</strong><small>Operational workflows, auth, APIs, relational data, admin surfaces.</small></div><div><span className="expertise-group-label">Mobile & edge</span><strong>Flutter · Dart · ESP32 · C++</strong><small>Offline-first apps, connected devices, telemetry, local persistence.</small></div><div><span className="expertise-group-label">Experience layer</span><strong>Three.js · Framer Motion · Tailwind</strong><small>High-signal art direction with speed, accessibility, and restraint.</small></div></div></div><div className="tech-strip"><span className="tech-label">Working toolkit</span><div className="tech-list">{technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></div></section>

    <section id="work" className="work-section section-frame"><div className="section-kicker"><span>03</span><span>Proof of work</span></div><div className="section-heading-row work-heading"><div><p className="eyebrow">Ten systems. One standard.</p><h2>Built for<br /><span>the real world.</span></h2></div><p className="section-intro">A selected body of commerce, healthcare, IoT, and store-technology products. Each case shows the thinking, tools, and operational depth behind the interface.</p></div><div className="project-list">{projects.map((project, index) => <ProjectCard key={project.name} project={project} index={index} />)}</div><div className="all-work-row"><span>15 public repositories on GitHub</span><a href="https://github.com/bassamdev711?tab=repositories" target="_blank" rel="noreferrer" className="text-link">View all repositories <ExternalLink size={15} /></a></div></section>

    <section id="contact" className="contact-section section-frame"><div className="contact-panel"><div className="contact-topline"><span>04 / Contact</span><span>Open to the right challenge</span></div><div className="contact-content"><p className="eyebrow"><span className="eyebrow-line" /> Start a conversation</p><h2>Have a complex idea?<br /><span>Let&apos;s give it shape.</span></h2><p>Whether you need a product from zero, a stronger technical foundation, or a second pair of eyes on a difficult system, I&apos;d be glad to hear what you&apos;re building.</p><a href="mailto:bassam.alhakim.dev@gmail.com" className="button button-light">bassam.alhakim.dev@gmail.com <ArrowUpRight size={17} /></a></div><div className="contact-links"><a href="https://github.com/bassamdev711" target="_blank" rel="noreferrer"><GithubMark size={17} /> GitHub</a><a href="https://www.linkedin.com/in/bassam-al-hakim-b4007a40b" target="_blank" rel="noreferrer"><BriefcaseBusiness size={17} /> LinkedIn</a><a href="tel:+967780500363"><Phone size={17} /> +967 780 500 363</a></div></div></section>
    <footer className="site-footer section-frame"><div className="footer-brand"><span className="brand-symbol">BA</span><span>© 2026 Bassam Alhakim</span></div><span>Designed, engineered, and shipped with intent.</span><a href="#top" className="footer-top">Back to top <ArrowUpRight size={15} /></a></footer>
  </main>;
}

function ProjectCard({ project, index }: { project: PortfolioProject; index: number }) {
  const isFeatured = index < 2;
  return <article className={`project-card ${isFeatured ? "project-card-featured" : "project-card-standard"} project-${project.accent}`}><div className="project-details"><div className="project-topline"><span>{project.eyebrow}</span><span>{project.number}</span></div><h3>{project.name}</h3><p className="project-title">{project.title}</p><p className="project-description">{project.description}</p><p className="project-impact"><Check size={15} /> {project.impact}</p><ProjectGallery project={project} featured={isFeatured} /><div className="project-bottom"><div className="project-stack">{project.stack.map((item) => <span key={item}>{item}</span>)}</div><div className="project-links"><a href={project.live} target="_blank" rel="noreferrer" className="text-link">View project <ArrowUpRight size={15} /></a><a href={project.external} target="_blank" rel="noreferrer" aria-label={`View ${project.name} source on GitHub`}><GithubMark size={17} /></a></div></div></div></article>;
}
