export type PortfolioProject = {
  number: string;
  eyebrow: string;
  title: string;
  name: string;
  description: string;
  impact: string;
  stack: readonly string[];
  image: string;
  gallery: readonly string[];
  live: string;
  external: string;
  accent: string;
};

const projectImages = (prefix: string, count: number) => Array.from({ length: count }, (_, index) => `/portfolio/${prefix}/${prefix}-${String(index + 1).padStart(2, "0")}.webp`);

export const projects: readonly PortfolioProject[] = [
  { number: "01", eyebrow: "Restaurant operations / ERP", title: "The operating system behind a serious restaurant business", name: "Restaurant ERP / إدارة المطعم", description: "A Laravel-powered restaurant management platform that connects point of sale, inventory, procurement, kitchen workflows, staff operations, reporting, and multi-surface control in one dependable system.", impact: "Point of sale · Inventory and procurement · Kitchen workflows · Reports and printing", stack: ["Laravel", "PHP", "Filament", "MySQL", "Tailwind CSS", "Laravel Reverb"], image: "/portfolio/restaurant/restaurant-01.webp", gallery: projectImages("restaurant", 26), live: "https://github.com/bassamdev711/restaurant-system", external: "https://github.com/bassamdev711/restaurant-system", accent: "blue" },
  { number: "02", eyebrow: "IoT / energy monitoring", title: "A live electrical telemetry system", name: "ESP32 Smart Meter / العداد الذكي", description: "An IoT system in which an ESP32 reads voltage and current, calculates power and energy, sends measurements to a PHP/MySQL backend, and exposes a web dashboard for live monitoring, alerts, reports, and remote relay control.", impact: "Real-time measurements · REST telemetry · Remote relay control · Dashboard and reports", stack: ["ESP32", "Arduino C++", "PHP", "MySQL", "JavaScript", "Chart.js"], image: "/portfolio/esp32/esp32-02.webp", gallery: projectImages("esp32", 14), live: "https://github.com/bassamdev711/esp32-smart-meter", external: "https://github.com/bassamdev711/esp32-smart-meter", accent: "cyan" },
  { number: "03", eyebrow: "Systems / mobile utility", title: "A focused telemetry layer for Android", name: "WiFi Monitor Pro / مراقب WiFi", description: "A Flutter and Kotlin-powered Android utility for monitoring per-app network consumption with a persistent foreground engine, local history, and security-focused overlays.", impact: "Per-app telemetry · Foreground service · Local history · Security overlay", stack: ["Flutter", "Kotlin Native", "Android SDK", "SQLite"], image: "/portfolio/wifi-monitor/wifi-monitor-06.webp", gallery: projectImages("wifi-monitor", 10), live: "https://github.com/bassamdev711/wifi-monitor-pro", external: "https://github.com/bassamdev711/wifi-monitor-pro", accent: "violet" },
  { number: "04", eyebrow: "Luxury commerce / 3D", title: "A cinematic fragrance boutique", name: "TIF / طيف", description: "A high-performance perfume storefront where quiet luxury meets real-time 3D. The experience treats product discovery as a sensory journey, with crystal-like preloading, tactile bottle visualization, and a fluid mobile catalog.", impact: "Real-time product visualization · Motion-led storytelling · Structured order transmission", stack: ["Next.js 16", "TypeScript", "Three.js", "React Three Fiber", "Framer Motion"], image: "/portfolio/atr/ora-tif-promo-01-laptop-hero.webp", gallery: ["/portfolio/atr/ora-tif-promo-03-catalog.webp", "/portfolio/atr/ora-tif-promo-04-admin-control.webp", "/portfolio/atr/ora-tif-promo-05-whitelabel.webp"], live: "https://tif-lyart.vercel.app/", external: "https://github.com/bassamdev711/tif", accent: "amber" },
  { number: "05", eyebrow: "Cultural commerce / retail", title: "A digital home for authentic flavor", name: "House of Spices / بيت البهارات", description: "A warm, localized commerce experience for a Yemeni spice and herb brand. From curated categories and premium saffron to mobile shopping, checkout, and store operations, the product turns heritage into a clear digital journey.", impact: "Localized product discovery · Editorial brand storytelling · Catalog-to-checkout commerce", stack: ["Next.js 16", "TypeScript", "Prisma", "PostgreSQL", "Vercel Blob"], image: "/portfolio/bharat/01-laptop-and-phone-home.webp", gallery: ["/portfolio/bharat/02-mobile-shopping-experience.webp", "/portfolio/bharat/03-product-to-checkout.webp", "/portfolio/bharat/04-admin-control-center.webp"], live: "https://house-of-spices-linl.vercel.app/", external: "https://github.com/bassamdev711/House_of_Spices", accent: "orange" },
  { number: "06", eyebrow: "Fashion commerce / editorial", title: "A quieter way to find the right step", name: "ATHR / أثر", description: "An editorial footwear store built around material, movement, and confident choice. The interface gives every collection room to breathe while supporting product discovery across men’s, women’s, children’s, formal, casual, and performance footwear.", impact: "Material-led art direction · Collection index · Clear sizing and purchase confidence", stack: ["Next.js 16", "TypeScript", "Prisma", "Framer Motion", "Tailwind CSS v4"], image: "/portfolio/hatha/01-athr-aura-hero-real.webp", gallery: ["/portfolio/hatha/02-athr-aura-mobile-real.webp", "/portfolio/hatha/03-athr-aura-laptop-real.webp", "/portfolio/hatha/06-aura-athr-admin-hero-real.webp"], live: "https://hitha711.vercel.app/", external: "https://github.com/bassamdev711/hitha", accent: "cyan" },
  { number: "07", eyebrow: "Luxury retail / timepieces", title: "Time, in a rarer form", name: "ORVÉN / أورفن", description: "A considered watch storefront shaped around restraint, precision, and collection. The system pairs a dark editorial identity with product lines from Editions and Obsidian to Skeleton, Marine, Heritage, and Chronograph.", impact: "Brand system · Curated product architecture · Commerce and control-room surfaces", stack: ["Next.js 16", "TypeScript", "Prisma", "GSAP", "Vercel Blob"], image: "/portfolio/saah/01-ora-soft-orven-identity.webp", gallery: ["/portfolio/saah/03-ora-soft-orven-commerce.webp", "/portfolio/saah/04-ora-soft-orven-control-room.webp", "/portfolio/saah/05-ora-soft-orven-analytics.webp"], live: "https://saahh.vercel.app/", external: "https://github.com/bassamdev711/saahh", accent: "violet" },
  { number: "08", eyebrow: "Home technology / energy", title: "A smarter operating layer for the home", name: "TAQA HOME / طاقة هوم", description: "An Arabic-first commerce platform for appliances, smart tools, solar energy, storage, and water heating. It connects clear product specifications with consultation, scalable catalogs, cart and checkout, administration, and after-sales confidence.", impact: "10 collections · 100-product catalog · Solar and storage commerce · Admin operations", stack: ["Next.js 16", "TypeScript", "Prisma", "PostgreSQL", "Framer Motion"], image: "/portfolio/taqt/aura-soft-taqa-home-real-01-hero.webp", gallery: ["/portfolio/taqt/aura-soft-taqa-home-real-02-mobile-story.webp", "/portfolio/taqt/aura-soft-taqa-home-real-05-catalog-post.webp", "/portfolio/taqt/aura-soft-taqa-admin-products-landscape.webp"], live: "https://taqa-gamma.vercel.app/", external: "https://github.com/bassamdev711/taqa", accent: "blue" },
  { number: "09", eyebrow: "Healthcare / patient experience", title: "Precision, with a human rhythm", name: "Dr. Layan Clinic / عيادة د. ليان", description: "A calm digital front door for cosmetic and restorative dentistry. The experience makes smile design, digital diagnosis, before-and-after transformation, and the first consultation feel clear, personal, and reassuring.", impact: "Personalized smile design · Consultation intake · Before/after storytelling · Secure validation", stack: ["Next.js 16", "TypeScript", "PostgreSQL", "Zod", "Vercel Blob"], image: "/portfolio/doctor/aura_soft_design_01.webp", gallery: ["/portfolio/doctor/aura_soft_design_02.webp", "/portfolio/doctor/aura_soft_design_03.webp", "/portfolio/doctor/aura_soft_design_05.webp"], live: "https://doctor-beta-dun.vercel.app/", external: "https://github.com/bassamdev711/doctor", accent: "rose" },
  { number: "10", eyebrow: "Offline-first retail / Flutter", title: "A dependable operating layer for the neighborhood store", name: "MATEEN / متين", description: "A Flutter-based store management system built to keep essential work moving without a constant internet connection. The app brings inventory, point of sale, purchasing, customers, suppliers, expenses, reports, and Arabic-first workflows into one focused operating surface, with a LAN display for larger screens.", impact: "Offline-first workflows · Local SQLite persistence · Arabic retail operations · Mobile-to-LAN display", stack: ["Flutter", "Dart", "Riverpod", "Drift / SQLite", "GoRouter", "PDF + Excel"], image: "/portfolio/maten/maten-01.webp", gallery: Array.from({ length: 19 }, (_, index) => `/portfolio/maten/maten-${String(index + 1).padStart(2, "0")}.webp`), live: "https://github.com/bassamdev711/baqkah", external: "https://github.com/bassamdev711/baqkah", accent: "cyan" },
];

export const capabilities = [
  { title: "Product architecture", description: "Turning ambiguous requirements into systems that are clear, extensible, and ready for real users." },
  { title: "Full-stack delivery", description: "Shipping the interface, API, database, and operational details as one coherent product surface." },
  { title: "Operational resilience", description: "Designing for authentication, background work, observability, performance, and the edge cases that matter." },
] as const;

export const technologies = ["Next.js", "TypeScript", "React Three Fiber", "Prisma", "PostgreSQL", "Laravel", "Flutter", "Vercel"] as const;
